accounts:
  - name: cntr-node1
    coins: ["5000000000000000000000000000cntr"]
validator:
  name: cntr-node1
  staked: "2500000000000000000000000cntr"
genesis:
  chain_id: "testnet"
  app_state:
    staking:
      params:
        bond_denom: "cntr"
    mint:
      params:
        mint_denom: "cntr"